/**
 * Object.observe Polyfill/shim
 * @jdarling : https://github.com/jdarling/Object.observe
**/
Object.observe||function(g,t){var x=function(a){var b=a.call(a),c=typeof c;return"object"===typeof t.alert?function(d){return b===a.call(d)||!!d&&typeof d.toString==c&&typeof d.valueOf==c&&/^\s*\bfunction\b/.test(""+d)}:function(d){return b===a.call(d)}}(g.prototype.toString),u=!!t.setImmediate,p=function(){return u?function(a){return setImmediate(a)}:function(a){return setTimeout(a,10)}}(),y=function(){return u?function(a){clearImmediate(a)}:function(a){clearTimeout(a)}}(),v=function(a){return!isNaN(parseFloat(a))&&
isFinite(a)},w=function(a,b,c){if("object"!==typeof a)throw new TypeError("Object.observeObject called on non-object");if(!1===x(b))throw new TypeError("Object.observeObject: Expecting function");if(!0===Object.isFrozen(b))throw new TypeError("Object.observeObject: Expecting unfrozen function");if(void 0!==c&&!Array.isArray(c))throw new TypeError("Object.observeObject: Expecting acceptList in the form of an array");},z=function(){var a=[],b=function(b,c,e){w(b,c,e);e||(e="add update delete reconfigure setPrototype preventExtensions".split(" "));
Object.getNotifier(b).addListener(c,e);-1===a.indexOf(b)?a.push(b):Object.getNotifier(b)._checkPropertyListing()};b.prototype.deliverChangeRecords=function(a){Object.getNotifier(a).deliverChangeRecords()};a.lastScanned=0;var c=function(a){return function e(){for(var b=0,c=a.length,g=new Date,k=!1,b=a.lastScanned;b<c&&!k;b++)-1<m.indexOf(a[b])?(Object.getNotifier(a[b])._checkPropertyListing(),k=100<new Date-g):(a.splice(b,1),b--,c--);a.lastScanned=b<c?b:0;p(e)}}(a);p(c);return b}(),A=function(a){var b=
[],c=[],d=[],g=!1,e=[],h=[],f=this;Object.defineProperty(f,"_watching",{enumerable:!0,get:function(k){return function(){return k}}(a)});var m=function(k,a){var b=Object.getOwnPropertyDescriptor(k,a),c;(c="getNotifier"===a)||(c="undefined"===typeof b?!1:"get"in b||"set"in b);if(c||!b.enumerable)return!1;if(k instanceof Array&&v(a))return b=e.length,e[b]=a,h[b]=k[a],!0;(function(b,a){e[b]=a;h[b]=k[a];Object.defineProperty(k,a,{get:function(){return h[b]},set:function(c){var q=h[b];if(q===c?0===q&&1/
q!==1/c:q===q||c===c)Object.getNotifier(k).queueUpdate(k,a,"update",h[b]),h[b]=c}})})(e.length,a);return!0};f._checkPropertyListing=function(b){var a=f._watching,c=Object.keys(a),d=0,g=c.length,r=e.slice(0),l=!b,s,n,p;a instanceof Array&&(p=f._oldLength);for(d=0;d<g;d++)b=c[d],s=a[b],-1===(n=e.indexOf(b))?m(a,b)&&l&&f.queueUpdate(a,b,"add",null,a[b]):(a instanceof Array&&!v(b)||h[n]===s||(l&&f.queueUpdate(a,b,"update",h[n],s),h[n]=s),r.splice(r.indexOf(b),1));a instanceof Array&&a.length!==p&&(l&&
f.queueUpdate(a,"length","update",p,a),f._oldLength=a.length);if(l)for(g=r.length,d=0;d<g;d++)n=e.indexOf(r[d]),f.queueUpdate(a,r[d],"delete",h[n]),e.splice(n,1),h.splice(n,1)};f.addListener=function(a,d){var f=b.indexOf(a);-1===f?(b.push(a),c.push(d)):c[f]=d};f.removeListener=function(a){a=b.indexOf(a);-1<a&&(b.splice(a,1),c.splice(a,1))};f.listeners=function(){return b};f.queueUpdate=function(a,b,c,d){this.queueUpdates([{type:c,object:a,name:b,oldValue:d}])};f.queueUpdates=function(a){for(var b=
this,c=0,f=a.length||0,e,c=0;c<f;c++)e=a[c],d.push(e);g&&y(g);g=p(function(){g=!1;b.deliverChangeRecords()})};f.deliverChangeRecords=function(){for(var a=0,f=b.length,a=0;a<f;a++)if(b[a]){var e;if(c[a]){e=[];for(var g=0,h=d.length;g<h;g++)-1!==c[a].indexOf(d[g].type)&&e.push(d[g])}else e=d;if(e.length)if(b[a]===console.log)console.log(e);else b[a](e)}d=[]};f.notify=function(b){if("object"!==typeof b||"string"!==typeof b.type)throw new TypeError("Invalid changeRecord with non-string 'type' property");
b.object=a;f.queueUpdates([b])};f._checkPropertyListing(!0)},l=[],m=[];g.getNotifier=function(a){var b=m.indexOf(a),b=-1<b?l[b]:!1;b||(b=m.length,m[b]=a,b=l[b]=new A(a));return b};g.observe=function(a,b,c){if(!("object"===typeof HTMLElement?a instanceof HTMLElement:a&&"object"===typeof a&&null!==a&&1===a.nodeType&&"string"===typeof a.nodeName))return new z(a,b,c)};g.unobserve=function(a,b){w(a,b);var c=m.indexOf(a),d=-1<c?l[c]:!1;d&&(d.removeListener(b),0===d.listeners().length&&(m.splice(c,1),l.splice(c,
1)))}}(Object,this);
